
#define DIAMETER_USER_NAME						1
#define DIAMETER_SIP_AOR						122
#define DIAMETER_HOST_IP_ADDRESS					257
#define DIAMETER_AUTH_APPLICATION_ID					258
#define DIAMETER_ACCT_APPLICATION_ID					259
#define DIAMETER_VENDOR_SPECIFIC_APPLICATION_ID				260
#define DIAMETER_SESSION_ID						263
#define DIAMETER_ORIGIN_HOST						264
#define DIAMETER_SUPPORTED_VENDOR_ID					265
#define DIAMETER_VENDOR_ID						266
#define DIAMETER_FIRMWARE_REVISION					267
#define DIAMETER_RESULT_CODE						268
#define DIAMETER_PRODUCT_NAME						269
#define DIAMETER_AUTH_SESSION_STATE					277
#define DIAMETER_ORIGIN_STATE_ID					278
#define DIAMETER_FAILED_AVP						279
#define DIAMETER_PROXY_HOST						280
#define DIAMETER_ROUTE_RECORD						282
#define DIAMETER_DESTINATION_REALM					283
#define DIAMETER_PROXY_INFO						284
#define DIAMETER_RE_AUTH_REQUEST_TYPE					285
#define DIAMETER_DESTINATION_HOST					293
#define DIAMETER_ORIGIN_REALM						296
#define DIAMETER_EXPERIMENTAL_RESULT					297
#define DIAMETER_INBAND_SECURITY_ID					299

#define DIAMETER_SUPPORTED_FEATURES

#define DIAMETER_MIP_HOME_AGENT_HOST					348
#define DIAMETER_SIP_ACCOUNTING_INFORMATION				368
#define DIAMETER_SIP_ACCOUNTING_SERVER_URI				369
#define DIAMETER_SIP_CREDIT_CONTROL_SERVER_URI				370
#define DIAMETER_SIP_SERVER_URI						371
#define DIAMETER_SIP_SERVER_CAPABILITIES				372
#define DIAMETER_SIP_MANDATORY_CAPABILITY				373
#define DIAMETER_SIP_OPTIONAL_CAPABILITY				374
#define DIAMETER_SIP_SERVER_ASSIGNMENT_TYPE				375
#define DIAMETER_SIP_AUTH_DATA_ITEM					376
#define DIAMETER_SIP_AUTHENTICATION_SCHEME				377
#define DIAMETER_SIP_ITEM_NUMBER					378
#define DIAMETER_SIP_AUTHENTICATE					379
#define DIAMETER_SIP_AUTHORIZATION					380
#define DIAMETER_SIP_AUTHENTICATION_INFO				381
#define DIAMETER_SIP_NUMBER_AUTH_ITEMS					382
#define DIAMETER_SIP_DEREGISTRATION_REASON				383
#define DIAMETER_SIP_REASON_CODE					384
#define DIAMETER_SIP_REASON_INFO					385
#define DIAMETER_SIP_VISITED_NETWORK_ID					386
#define DIAMETER_SIP_USER_AUTHORIZATION_TYPE				387
#define DIAMETER_SIP_SUPPORTED_USER_DATA_TYPE				388
#define DIAMETER_SIP_USER_DATA						389
#define DIAMETER_SIP_USER_DATA_TYPE					390
#define DIAMETER_SIP_USER_DATA_CONTENTS					391
#define DIAMETER_SIP_USER_DATA_ALREADY_AVAILABLE			392
#define DIAMETER_SIP_METHOD						393

#define DIAMETER_MIP6_AGENT_INFO					486
#define DIAMETER_SERVICE_SELECTION					493

#define DIAMETER_VISITED_NETWORK_IDENTIFIER				600
#define DIAMETER_OC_SUPPORTED_FEATURES					620
#define DIAMETER_OC_FEATURE_VECTOR					622
#define DIAMETER_OC_PEER_ALGO						648
#define DIAMETER_SOURCEID						649

#define DIAMETER_RAT_TYPE						1032

#define DIAMETER_SUBSCRIPTION_DATA					1400
#define DIAMETER_TERMINAL_INFORMATION					1401
#define DIAMETER_ULR_FLAGS						1405
#define DIAMETER_ULA_FLAGS						1406
#define DIAMETER_VISITED_PLMN_ID					1407
#define DIAMETER_REQUESTED_EUTRAN_AUTHENTICATION_INFO			1408
#define DIAMETER_REQUESTED_UTRAN_GERAN_AUTHENTICATION_INFO		1409
#define DIAMETER_NUMBER_OF_REQUESTED_VECTORS				1410
#define DIAMETER_RE_SYNCHRONIZATION_INFO				1411
#define DIAMETER_IMMEDIATE_RESPONSE_PREFERRED				1412

#define DIAMETER_CONTEXT_IDENTIFIER					1423
#define DIAMETER_APN_CONFIGURATION					1430
#define DIAMETER_VPLMN_DYNAMIC_ADDRESS_ALLOWED				1432
#define DIAMETER_IDR_FLAGS						1490
#define DIAMETER_ICS_INDICATOR						1491
#define DIAMETER_USER_ID						1444
#define DIAMETER_SGSN_NUMBER						1489
#define DIAMETER_HOMOGENEOUS_SUPPORT_OF_IMS_VOICE_OVER_PS_SESSIONS	1493

#define DIAMETER_ACTIVE_APN						1612
#define DIAMETER_UE_SRVCC_CAPABILITY					1615
#define DIAMETER_EVENT_THRESHOLD_RSRQ					1629
#define DIAMETER_PUR_FLAGS						1635
#define DIAMETER_EQUIVALENT_PLMN_LIST					1637
#define DIAMETER_A_MSISDN						1643
#define DIAMETER_MME_NUMBER_FOR_MT_SMS					1645
#define DIAMETER_SMS_REGISTER_REQUEST					1648
#define DIAMETER_SGS_MME_IDENTITY					1664
#define DIAMETER_COUPLED_NODE_DIAMETER_ID				1666
#define DIAMETER_GROUP_PLMN_ID						1677

#define DIAMETER_GMLC_ADDRESS						2405

#define DIAMETER_UE_REACHABILITY_CONFIGURATION				3129
#define DIAMETER_ACCURACY						3136
#define DIAMETER_REACHABILITY_TYPE
#define DIAMETER_EPS_USER_STATE
#define DIAMETER_PRE_EMPTION_CAPABILITY
#define DIAMETER_FEATURE_LIST_ID
#define DIAMETER_SERVICE_AREA_IDENTITY
#define DIAMETER_DAY_OF_WEEK_MASK
#define DIAMETER_ALL_APN_CONFIGURATIONS_INCLUDED_INDICATOR
#define DIAMETER_E_UTRAN_VECTOR
#define DIAMETER_PUA_FLAGS
#define DIAMETER_MAXIMUM_RESPONSE_TIME
#define DIAMETER_CSG_ACCESS_MODE
#define DIAMETER_ADDITIONAL_CONTEXT_IDENTIFIER
#define DIAMETER_ACCESS_RESTRICTION_DATA
#define DIAMETER_MIP_HOME_LINK_PREFIX
#define DIAMETER_GPRS_SUBSCRIPTION_DATA
#define DIAMETER_SRES
#define DIAMETER_LOAD_VALUE
#define DIAMETER_FEATURE_LIST
#define DIAMETER_APN_OI_REPLACEMENT
#define DIAMETER_MONITORING_EVENT_CONFIG_STATUS
#define DIAMETER_OC_REPORT_TYPE
#define DIAMETER_EDRX_CYCLE_LENGTH
#define DIAMETER_IMS_VOICE_OVER_PS_SESSIONS_SUPPORTED
#define DIAMETER_UE_USAGE_TYPE
#define DIAMETER_LCS_PRIVACYEXCEPTION
#define DIAMETER_VX_SUBSCRIPTION_DATA
#define DIAMETER_ADJACENT_ACCESS_RESTRICTION_DATA
#define DIAMETER_QOS_CLASS_IDENTIFIER
#define DIAMETER_EXT_PDP_TYPE
#define DIAMETER_RELAY_NODE_INDICATOR
#define DIAMETER_COMMUNICATION_DURATION_TIME
#define DIAMETER_ITEM_NUMBER
#define DIAMETER_LIST_OF_MEASUREMENTS
#define DIAMETER_GERAN_VECTOR
#define DIAMETER_EPS_LOCATION_INFORMATION
#define DIAMETER_DRMP
#define DIAMETER_TRACE_NE_TYPE_LIST
#define DIAMETER_ADJACENT_PLMNS
#define DIAMETER_PRIORITY_LEVEL
#define DIAMETER_PRE_EMPTION_VULNERABILITY
#define DIAMETER_GEODETIC_INFORMATION
#define DIAMETER_LOAD_TYPE
#define DIAMETER_AREA_SCOPE
#define DIAMETER_PREFERRED_DATA_MODE
#define DIAMETER_IMEI
#define DIAMETER_REACHABILITY_INFORMATION
#define DIAMETER_NODE_TYPE
#define DIAMETER_CLR_FLAGS
#define DIAMETER_CALL_BARRING_INFO
#define DIAMETER_SERVICE_REPORT
#define DIAMETER_LOCATION_AREA_IDENTITY
#define DIAMETER_LOGGING_INTERVAL
#define DIAMETER_ROAMING_RESTRICTED_DUE_TO_UNSUPPORTED_FEATURE
#define DIAMETER_EDRX_CYCLE_LENGTH_VALUE
#define DIAMETER_TIME_ZONE
#define DIAMETER_MSISDN
#define DIAMETER_MO_LR
#define DIAMETER_JOB_TYPE
#define DIAMETER_SS_CODE
#define DIAMETER_TIME_OF_DAY_START
#define DIAMETER_WLAN_OFFLOADABILITY
#define DIAMETER_PDN_TYPE
#define DIAMETER_COMMUNICATION_PATTERN_SET
#define DIAMETER_PERIODIC_COMMUNICATION_INDICATOR
#define DIAMETER_PROSE_PERMISSION
#define DIAMETER_CHARGED_PARTY
#define DIAMETER_SUPPORTED_SERVICES
#define DIAMETER_3GPP_CHARGING_CHARACTERISTICS
#define DIAMETER_SUBSCRIBED_PERIODIC_RAU_TAU_TIMER
#define DIAMETER_SS_STATUS
#define DIAMETER_ENODEB_ID
#define DIAMETER_UTRAN_VECTOR
#define DIAMETER_MONTE_LOCATION_TYPE
#define DIAMETER_LAST_UE_ACTIVITY_TIME
#define DIAMETER_LOCAL_TIME_ZONE
#define DIAMETER_AUTHENTICATION_INFO
#define DIAMETER_SERVICE_TYPE
#define DIAMETER_VX_PERMISSION
#define DIAMETER_PDP_ADDRESS
#define DIAMETER_IMSI_GROUP_ID
#define DIAMETER_DSR_FLAGS
#define DIAMETER_COMPLETE_DATA_LIST_INCLUDED_INDICATOR
#define DIAMETER_TRACE_COLLECTION_ENTITY
#define DIAMETER_WLAN_OFFLOADABILITY_EUTRAN
#define DIAMETER_REFERENCE_ID_VALIDITY_TIME
#define DIAMETER_DL_BUFFERING_SUGGESTED_PACKET_COUNT
#define DIAMETER_SCEF_ID
#define DIAMETER_TRACE_EVENT_LIST
#define DIAMETER_CSG_ID
#define DIAMETER_MDT_CONFIGURATION
#define DIAMETER_ERROR_DIAGNOSTIC
#define DIAMETER_ROUTING_AREA_IDENTITY
#define DIAMETER_CURRENT_LOCATION_RETRIEVED
#define DIAMETER_USER_CSG_INFORMATION
#define DIAMETER_MIP_AGENT_INFO
#define DIAMETER_LOGGING_DURATION
#define DIAMETER_COLLECTION_PERIOD_RRM_UMTS
#define DIAMETER_IDA_FLAGS
#define DIAMETER_NON_IP_PDN_TYPE_INDICATOR
#define DIAMETER_TRACKING_AREA_IDENTITY
#define DIAMETER_OC_OLR
#define DIAMETER_CLIENT_IDENTITY
#define DIAMETER_AGE_OF_LOCATION_INFORMATION
#define DIAMETER_TRACE_DATA
#define DIAMETER_SUBSCRIBED_VSRVCC
#define DIAMETER_PLMN_CLIENT
#define DIAMETER_VPLMN_LIPA_ALLOWED
#define DIAMETER_AIR_FLAGS
#define DIAMETER_SPECIFIC_APN_INFO
#define DIAMETER_RAND
#define DIAMETER_OC_REDUCTION_PERCENTAGE
#define DIAMETER_REPORT_INTERVAL
#define DIAMETER_EPS_SUBSCRIBED_QOS_PROFILE
#define DIAMETER_SERVICE_RESULT_CODE
#define DIAMETER_OMC_ID
#define DIAMETER_OC_SEQUENCE_NUMBER
#define DIAMETER_TELESERVICE_LIST
#define DIAMETER_APN_CONFIGURATION_PROFILE
#define DIAMETER_EVENT_THRESHOLD_EVENT_I
#define DIAMETER_SUPPORTED_MONITORING_EVENTS
#define DIAMETER_DSA_FLAGS
#define DIAMETER_EVENT_THRESHOLD_EVENT_F
#define DIAMETER_ALLOCATION_RETENTION_PRIORITY
#define DIAMETER_CELL_GLOBAL_IDENTITY
#define DIAMETER_OC_VALIDITY_DURATION
#define DIAMETER_CSG_MEMBERSHIP_INDICATION
#define DIAMETER_NETWORK_ACCESS_MODE
#define DIAMETER_3GPP_MEID
#define DIAMETER_MME_LOCATION_INFORMATION
#define DIAMETER_SGSN_LOCATION_INFORMATION
#define DIAMETER_MEASUREMENT_PERIOD_LTE
#define DIAMETER_GMLC_RESTRICTION
#define DIAMETER_USER_STATE
#define DIAMETER_KC
#define DIAMETER_WLAN_OFFLOADABILITY_UTRAN
#define DIAMETER_SERVICETYPEIDENTITY
#define DIAMETER_STN_SR
#define DIAMETER_NOTIFICATION_TO_UE_USER
#define DIAMETER_PDP_CONTEXT
#define DIAMETER_MAX_REQUESTED_BANDWIDTH_DL
#define DIAMETER_TRACE_INTERFACE_LIST
#define DIAMETER_PDN_CONNECTION_CONTINUITY
#define DIAMETER_SCEF_REFERENCE_ID
#define DIAMETER_RAT_FREQUENCY_SELECTION_PRIORITY_ID
#define DIAMETER_SUBSCRIPTION_DATA_DELETION
#define DIAMETER_LOAD
#define DIAMETER_INTEGRITY_KEY
#define DIAMETER_CONFIDENTIALITY_KEY
#define DIAMETER_E_UTRAN_CELL_GLOBAL_IDENTITY
#define DIAMETER_MONITORING_TYPE
#define DIAMETER_UE_PC_AMBR
#define DIAMETER_EVENT_THRESHOLD_RSRP
#define DIAMETER_XRES
#define DIAMETER_SUBSCRIBER_STATUS
#define DIAMETER_EXPERIMENTAL_RESULT_CODE
#define DIAMETER_COLLECTION_PERIOD_RRM_LTE
#define DIAMETER_MAXIMUM_NUMBER_OF_REPORTS
#define DIAMETER_HPLMN_ODB
#define DIAMETER_MME_USER_STATE
#define DIAMETER_RESET_ID
#define DIAMETER_LIPA_PERMISSION
#define DIAMETER_MPS_PRIORITY
#define DIAMETER_MONITORING_EVENT_REPORT
#define DIAMETER_EXTENDED_ENODEB_ID
#define DIAMETER_AESE_COMMUNICATION_PATTERN
#define DIAMETER_LCS_INFO
#define DIAMETER_RESTORATION_PRIORITY
#define DIAMETER_MDT_USER_CONSENT
#define DIAMETER_CANCELLATION_TYPE
#define DIAMETER_STATIONARY_INDICATION
#define DIAMETER_PDN_GW_ALLOCATION_TYPE
#define DIAMETER_GMLC_NUMBER
#define DIAMETER_SUBSCRIPTION_DATA_FLAGS
#define PROPERTY__AVP_VISITED_PLMN_ID__MCC
#define PROPERTY__AVP_VISITED_PLMN_ID__MNC
#define DIAMETER_QOS_SUBSCRIBED
#define DIAMETER_POSITIONING_METHOD
#define DIAMETER_MONITORING_DURATION
#define DIAMETER_REPORTING_TRIGGER
#define DIAMETER_AMBR
#define DIAMETER_DAYLIGHT_SAVING_TIME
#define DIAMETER_EXPIRATION_DATE
#define DIAMETER_GROUP_SERVICE_ID
#define DIAMETER_TRACE_REFERENCE
#define DIAMETER_LOCAL_GROUP_ID
#define DIAMETER_MEASUREMENT_QUANTITY
#define DIAMETER_GEOGRAPHICAL_INFORMATION
#define DIAMETER_KASME
#define DIAMETER_SERVED_PARTY_IP_ADDRESS
#define DIAMETER_TRACE_DEPTH
#define DIAMETER_SCHEDULED_COMMUNICATION_TIME
#define DIAMETER_PROXY_STATE
#define DIAMETER_OPERATOR_DETERMINED_BARRING
#define DIAMETER_AUTN
#define DIAMETER_PDP_TYPE
#define DIAMETER_PERIODIC_TIME
#define DIAMETER_TIME_OF_DAY_END
#define DIAMETER_SOFTWARE_VERSION
#define DIAMETER_SIPTO_LOCAL_NETWORK_PERMISSION
#define DIAMETER_SGSN_USER_STATE
#define DIAMETER_MAX_REQUESTED_BANDWIDTH_UL
#define DIAMETER_NON_IP_DATA_DELIVERY_MECHANISM
#define DIAMETER_MONITORING_EVENT_CONFIGURATION
#define DIAMETER_SCEF_REALM
#define DIAMETER_SIPTO_PERMISSION
#define DIAMETER_EMERGENCY_INFO
#define DIAMETER_MDT_ALLOWED_PLMN_ID
#define DIAMETER_REPORT_AMOUNT
#define DIAMETER_CSG_SUBSCRIPTION_DATA
#define DIAMETER_EXTERNAL_CLIENT
#define DIAMETER_MIP_HOME_AGENT_ADDRESS
#define DIAMETER_MEASUREMENT_PERIOD_UMTS
#define DIAMETER_SCEF_REFERENCE_ID_FOR_DELETION
#define DIAMETER_PROSE_SUBSCRIPTION_DATA
#define DIAMETER_SERVICE_RESULT
#define DIAMETER_LOCATION_INFORMATION_CONFIGURATION
#define DIAMETER_EXT_PDP_ADDRESS
#define DIAMETER_REGIONAL_SUBSCRIPTION_ZONE_CODE
#define DIAMETER_TS_CODE
#define PACKET_FIELD_SRC_IP
#define PACKET_FIELD_DST_IP
